name: Build and Upload Artifact

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t aurum-builder .

    - name: Run Docker Container
      run: docker run -v $(pwd):/tmp/ aurum-builder

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: aurumOS UNSTABLE image
        path: /tmp/aurumOS_unstable.iso
